backend:
  name: github
  repo: CoenPrins/blaaskaak
  branch: main
media_folder: static/media
public_folder: /media
site_url: https://blaaskaak.nl
display_url: https://blaaskaak.nl
logo:
  src: https://blaaskaak.nl/media/logo-round.webp
  show_in_header: true
collections:
  - name: pages
    label: Pages
    label_singular: Page
    create: true
    editor:
      preview: false
    files:
      - file: content/over-ons.md
        name: over-ons
        label: Over Ons
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: Layout, hidden: true, name: layout, default: page }
          - { label: Text Coen, name: params.textCoen, widget: markdown }
          - { label: Text Fabio, name: params.textFabio, widget: markdown }
          - { label: Text Ivar, name: params.textIvar, widget: markdown }
          - { label: Content, name: body, widget: markdown }

  - name: settings
    label: Site settings
    editor:
      preview: false
    files:
      - label: Menu
        name: nav
        file: data/nav.yml
        fields:
          - label: Items
            name: nav
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Page URL (e.g. /over-ons/)", name: "page", widget: "string" }
      - file: data/basics.yml
        label: Basics
        name: basics
        fields:
          - { label: Logo, name: logo, widget: image }
          - { label: Share logo, name: sharelogo, widget: image }
          - { label: Short Description, name: shortDescription, widget: text }
          - { label: Long Description, name: longDescription, widget: text }
      - file: data/socials.yml
        label: Socials
        name: socials
        fields:
          - label: Items
            name: socials
            widget: list
            fields:
              - { name: "type", label: "Type", widget: "string" }
              - { name: "username", label: "Display name", widget: "string" }
              - { name: "url", label: "Link", widget: "string" }
