backend:
  name: github
  repo: CoenPrins/blaaskaak
  branch: admin-panel # TODO
media_folder: static/media
public_folder: /media
site_url: https://blaaskaak.nl # TODO?
display_url: https://blaaskaak.nl
logo:
  src: https://blaaskaak.nl/media/logo-slechte-kwali.png
  show_in_header: true
collections:
  - name: pages
    label: Pages
    label_singular: Page
    create: true
    editor:
      preview: false
    folder: content
    fields:
      - label: Title (also becomes the URL)
        hint: Page URL cannot be changed afterwards!
        name: title
        widget: string
      - label: Content
        name: body
        widget: markdown

  - name: settings
    label: Site settings
    editor:
      preview: false
    files:
      - label: Menu
        name: nav
        file: data/nav.yml
        fields:
          - label: Items
            name: nav
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Page URL (e.g. /over-ons/)", name: "page", widget: "string" }
      - file: data/basics.yml
        label: Basics
        name: basics
        fields:
          - label: Icon
            name: icon
            widget: image
      - file: data/socials.yml
        label: Socials
        name: socials
        fields:
          - label: Items
            name: socials
            widget: list
            fields:
              - { name: "type", label: "Type", widget: "string" }
              - { name: "username", label: "Display name", widget: "string" }
              - { name: "url", label: "Link", widget: "string" }
