backend:
  name: github
  repo: CoenPrins/blaaskaak
  branch: admin-panel
media_folder: static/media
public_folder: /media
collections:
  - name: overig
    label: Overig
    editor:
      preview: false
    files:
      - label: "Navigatiebalk"
        name: "navigation"
        file: "data/nav.yml"
        fields:
          - label: "Items"
            name: "nav"
            widget: "list"
            fields:
              - { label: "Naam", name: "name", widget: "string" }
              - { label: "Pagin URL (bijv. /over-ons/)", name: "page", widget: "string" }

  - name: paginas
    label: Pagina's
    label_singular: Pagina
    create: true
    editor:
      preview: false
    folder: content
    fields:
      - label: Naam
        name: title
        widget: string
      - label: Tekst
        name: body
        widget: markdown
